<?php $this->headTitle('About'); ?>
<h1> About <?php echo $this->organization ?> <small> - Who we are?</small></h1>
<div class="row">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet, sem vitae faucibus finibus, leo est condimentum orci, eget lobortis urna orci sed ligula. Aliquam id elementum ante, non sodales lorem. Ut tristique justo molestie eros mollis, pulvinar mollis arcu lacinia. Cras ac tristique ante, id viverra velit. Nulla dui sapien, tristique sit amet quam non, mollis congue purus. Nunc dictum dui eget pretium sollicitudin. Nulla suscipit tincidunt sagittis. Vivamus nisi leo, iaculis nec venenatis id, sagittis a turpis. Pellentesque accumsan odio eget neque consectetur semper in non dui. Curabitur at nisl volutpat, egestas tellus a, luctus purus. Nullam suscipit auctor est porta sodales. Pellentesque eu congue felis.
    </p>

    <p>
        Vivamus pretium nisi turpis, at congue velit luctus sit amet. Praesent euismod varius euismod. Duis lorem elit, accumsan id eleifend a, efficitur ac dolor. Vestibulum in consequat augue. Ut congue dictum nisl accumsan facilisis. Donec at dolor ut quam commodo elementum a vitae sapien. Nullam molestie commodo risus, a consectetur justo. Ut porta est et sapien consequat consectetur. Cras condimentum vel purus ut molestie. Suspendisse hendrerit lorem at est consequat, auctor volutpat erat condimentum. Morbi sodales viverra ipsum, at efficitur odio aliquam et. Proin nec lectus aliquam, elementum elit lacinia, semper lacus. Sed finibus porttitor ipsum eu gravida.
    </p>
</div>
<div class="divider"><hr></div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Follow Development</h3>
            </div>
            <div class="panel-body">
                <p>
                    Duis pellentesque sem vitae metus semper mollis. Praesent convallis porttitor neque sit amet tincidunt. Vivamus egestas, neque sed imperdiet tristique, metus erat faucibus ante, nec consequat mi sem et purus. Sed congue, dui ac pharetra blandit, nunc magna ultricies neque, nec congue orci sapien ut sapien. Quisque tempor non erat vel convallis. Nam sed neque aliquet, consectetur arcu vel, euismod quam. Sed vulputate sapien quis congue varius. Phasellus fermentum orci vitae augue dictum, nec finibus tellus feugiat. Aenean dapibus odio vel volutpat facilisis. Donec vulputate scelerisque ante, nec placerat est auctor ultricies. In sit amet fermentum velit. Nulla mi arcu, auctor et pretium eu, auctor sed orci. Nulla nisl ante, pellentesque in elit ac, egestas imperdiet sem.
                </p>                
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">
                <p>
                    Maecenas aliquet tortor ut erat malesuada, id condimentum elit interdum. Integer scelerisque egestas turpis, eget pulvinar mauris aliquet tincidunt. Nam vulputate sed lectus nec ultricies. Praesent molestie tincidunt turpis, eget bibendum arcu placerat sit amet. Etiam sodales quam eget diam cursus, ut luctus nunc blandit. Mauris aliquet varius enim vel ultricies. Proin eleifend, metus ut fringilla pulvinar, nunc nibh tempus ligula, id pulvinar turpis augue vitae mi. Morbi laoreet quam at ultricies porttitor. Proin malesuada, lorem sit amet vulputate tincidunt, sapien nibh lobortis nibh, at imperdiet felis urna quis massa. Morbi egestas enim at tempor condimentum. Proin consequat dolor ante, quis ornare justo tempus non. Morbi quis purus viverra, efficitur arcu sed, commodo dolor. Praesent bibendum et nisl et interdum. Integer scelerisque, leo et suscipit porta, quam nisi venenatis lacus, non accumsan ante tellus vel magna.
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                    Pellentesque in massa justo. Duis sagittis maximus mollis. Vestibulum vitae felis eu metus malesuada feugiat quis ut sem. Sed aliquet nisl ac rhoncus vestibulum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut lacus ligula, consequat et venenatis maximus, placerat eget risus. Nullam ut odio nisl.
                </p>
            </div>
        </div>
    </div>
</div>