<?php $this->plugin('basePath')->setBasePath("/"); ?>

<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->application_name)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/assets/application/img/favicon.ico'])
                        ->prependStylesheet($this->basePath() . '/assets/application/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/application/css/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/application/css/plugins/morris.css')
                        ->prependStylesheet($this->basePath() . '/assets/font-awesome/css/font-awesome.min.css')
                    ;
        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/jquery/jquery.min.js')
            ->prependFile($this->basePath() . '/assets/application/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/application/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"> 
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"> <?php echo $this->application_name; ?> </a>
                    </div>
                    <div class="navbar-collapse collapse navbar-inverse-collapse">
                        <?php                             
//                            echo $this->navigation('navigation')
//                                    ->menu()
//                                    ->setUlClass('nav navbar-nav')
//                                    ->setPartial('template/navigation');
                        ?>                        
                    </div>
                </nav>
            </div>
            <div class="row">
                <?php // echo $this->navigation()->breadcrumbs()->setPartial('template/breadcrumbs'); ?>
            </div>
            <div class="row">
                <?php echo $this->content;?>                
            </div>
            <div class="row">
                <?php echo $this->partial('template/footer', ['org'=>$this->organization, 'year' => $this->copyright_year]); ?>
            </div>
        </div>
    </body>
</html>
